name: Rebuild website
on:
  schedule:
    - cron: '12 1 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
            ref: main
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Gather information
        run: python3 scripts/gather.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build site
        run: python3 scripts/build-site.py
      - uses: stefanzweifel/git-auto-commit-action@v6
        name: Commit downloaded fonts and data
