name: Megamerge
on:
  schedule:
    - cron: '12 3 1 * *'

jobs:
  megamerge:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v5
        with:
            ref: main
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      # We need harfbuzz for optimal packing!
      - name: Install harfbuzz
        uses: notofonts/install-harfbuzz-action@main
      - name: Install dependencies
        run: pip install fontTools gftools uharfbuzz
      - name: Merge the fonts
        run: cd megamerge; python3 megamerge.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "megamerge/*ttf"
          commit_message: "Update megamerged files"
        name: Commit
